### numpy

In [ ]:
-stands for numerical python
-its a library consisting of multi dimentional array objects and collection of routine
 for processing those arrays


In [2]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [6]:
list_of_lists=([1,2,3],[4,5,6],[7,8,9])
sample_matrix=np.array(list_of_lists)
print(sample_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [9]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [10]:
np.arange(1,46,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [13]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### create an array of zero with 2 rows and 10 columns

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [20]:
np.eye(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(3,2)

array([[0.61146907, 0.97045151],
       [0.92746001, 0.99026439],
       [0.26828247, 0.34469458]])

In [22]:
np.random.randn(3,2)

array([[ 0.43129917, -1.04435909],
       [-2.28961913,  0.003688  ],
       [-0.20216227,  0.46838364]])

In [23]:
np.random.randint(34,100)

56

In [24]:
np.random.randint(34,100,50)

array([66, 59, 74, 80, 74, 68, 93, 34, 92, 35, 85, 62, 84, 38, 37, 82, 68,
       53, 77, 60, 60, 84, 46, 66, 87, 46, 95, 97, 39, 58, 89, 47, 69, 58,
       41, 45, 63, 84, 77, 92, 60, 78, 72, 98, 84, 81, 34, 84, 76, 83])

In [26]:
sample_array=np.arange(30)
print(sample_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [27]:
rand_array=np.random.randint(0,100,20)
print(rand_array)

[33 60 74 18 67 10 61 45 85 16 30 13  5 35 24 47 34 29 29  4]


In [28]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [108]:
rand_array.min()

4

In [109]:
rand_array.argmin()

19

In [110]:
sample_array.dtype

dtype('int32')

In [111]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [112]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [113]:
a=np.random.rand(2,3)
a

array([[0.12221765, 0.13822936, 0.49776638],
       [0.0286027 , 0.9175639 , 0.60384901]])

In [114]:
a.T

array([[0.12221765, 0.0286027 ],
       [0.13822936, 0.9175639 ],
       [0.49776638, 0.60384901]])

In [115]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [38]:
sample_array[3]

13

In [39]:
sample_array[3:7]

array([13, 14, 15, 16])

In [40]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [41]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [43]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [44]:
subset_sample_array[1:4]=1001
subset_sample_array

array([  10, 1001, 1001, 1001,   14,   15,   16])

In [45]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### two dimentional array

In [47]:
import numpy as np

In [48]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[53,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [53, 76, 24,  7]])

In [49]:
sample_matrix[2][3]

7

In [50]:
sample_matrix[0:2,2]

array([ 1, 21])

In [51]:
sample_matrix[2,:]

array([53, 76, 24,  7])

In [52]:
sample_matrix[2]

array([53, 76, 24,  7])

In [53]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [56]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [57]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [58]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [59]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [60]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [61]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [62]:
np.max(sample_array)

19

In [63]:
np.min(sample_array)

1

In [64]:
np.argmax(sample_array)

18

In [66]:
np.argmin(sample_array)

0

In [67]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361], dtype=int32)

In [68]:
np.std(sample_array)

5.477225575051661

In [69]:
np.mean(sample_array)

10.0

In [70]:
np.var(sample_array)

30.0

In [71]:
array=np.random.randn(3,4)
array

array([[-2.29849018, -0.12182266,  1.62961004,  0.79359527],
       [ 0.28314289, -1.62402068, -0.94549278, -1.20640024],
       [ 1.59115687,  0.2839164 ,  2.14955535, -0.39025595]])

In [74]:
np.round(array,decimals=3)
array

array([[-2.29849018, -0.12182266,  1.62961004,  0.79359527],
       [ 0.28314289, -1.62402068, -0.94549278, -1.20640024],
       [ 1.59115687,  0.2839164 ,  2.14955535, -0.39025595]])

In [75]:
sports=np.array(['golf','cricket','fball','circket','fball','basketball'])
np.unique(sports)

array(['basketball', 'circket', 'cricket', 'fball', 'golf'], dtype='<U10')

### other references on numpy

### one dimentional array

In [76]:
import numpy as np
var1=np.array([2,3,4])
print(var1)

[2 3 4]


### two dimentional array

In [78]:
import numpy as np
var1=np.array([(2,4,6),(1,3,5)])
print(var1)

[[2 4 6]
 [1 3 5]]


### addition of arrays

In [79]:
import numpy as np
var1=np.array([(2,4,6),(1,3,5)])
var2=np.array([(3,5,7),(8,7,6)])
print(var1+var2)

[[ 5  9 13]
 [ 9 10 11]]


### item size

In [80]:
import numpy as np
var1=np.array([2,4,6])
print(var1.itemsize)

4


### data type

In [81]:
import numpy as np
var1=np.array([2,4,6])
print(var1.dtype)

int32


### how many dimensional inside an array

In [82]:
import numpy as np
var1=np.array([(2,3,4),(4,5,6)])
print(var1.ndim)

2


### size of an array

In [83]:
import numpy as np
var1=np.array([(2,3,4),(5,6,7),(8,9,1)])
print(var1)
print(var1.size)

[[2 3 4]
 [5 6 7]
 [8 9 1]]
9


### shape of an array (no.of rows and columns)

In [84]:
import numpy as np
var1=np.array([(2,3,4),(5,6,7)])
print(var1)
print(var1.shape)

[[2 3 4]
 [5 6 7]]
(2, 3)


### reshape of an array (changing of rows to columns,columns to rows)


In [85]:
import numpy as np
var1=np.array([(2,3,4),(5,6,7)])
var1=var1.reshape(3,2)
print(var1)
print(var1.shape)

[[2 3]
 [4 5]
 [6 7]]
(3, 2)


### creating an array

In [ ]:
linspace(linear space):creates an array with num of equal distance
    

In [87]:
import numpy as np
var1=np.linspace(10,20,20)
print(var1)

[10.         10.52631579 11.05263158 11.57894737 12.10526316 12.63157895
 13.15789474 13.68421053 14.21052632 14.73684211 15.26315789 15.78947368
 16.31578947 16.84210526 17.36842105 17.89473684 18.42105263 18.94736842
 19.47368421 20.        ]


### slicing an array

In [88]:
import numpy as np
var1=np.array([(2,3,4),(1,5,7)])
print(var1[1:])

[[1 5 7]]


In [92]:
import numpy as np
var1=np.array([(2,3,4),(1,5,7)])
print(var1[0:,1])

[3 5]


In [93]:
import numpy as np
var1=np.array([(2,3,4),(1,5,7)])
print(var1[0,1])

3


In [95]:
import numpy as np
var1=np.array([(1,2,3),(4,5,6),(7,8,9),(10,11,12)])
print(var1[1:,1])

[ 5  8 11]


### min max and sum operations on array

In [96]:
import numpy as np
var1=np.array([2,4,6])
print(var1.min())

2


In [97]:
import numpy as np
var1=np.array([2,4,6])
print(var1.max())

6


In [98]:
import numpy as np
var1=np.array([2,4,6])
print(var1.sum())

12


### basic operations on matrix

In [99]:
import numpy as np
var1=np.array([(2,4,6),(1,3,5)])
var2=np.array([(3,5,7),(8,7,6)])
print(var1+var2)

[[ 5  9 13]
 [ 9 10 11]]


In [100]:
import numpy as np
var1=np.array([(2,4,6),(1,3,5)])
var2=np.array([(3,5,7),(8,7,6)])
print(var1-var2)

[[-1 -1 -1]
 [-7 -4 -1]]


In [101]:
import numpy as np
var1=np.array([(2,4,6),(1,3,5)])
var2=np.array([(3,5,7),(8,7,6)])
print(var1*var2)

[[ 6 20 42]
 [ 8 21 30]]


In [102]:
import numpy as np
var1=np.array([(2,4,6),(1,3,5)])
var2=np.array([(3,5,7),(8,7,6)])
print(var1/var2)

[[0.66666667 0.8        0.85714286]
 [0.125      0.42857143 0.83333333]]


In [103]:
import numpy as np
var1=np.array([(2,4,6),(1,3,5)])
var2=np.array([(3,5,7),(8,7,6)])
print(var1%var2)

[[2 4 6]
 [1 3 5]]


In [104]:
import numpy as np
var1=np.array([(2,4,6),(1,3,5)])
var2=np.array([(3,5,7),(8,7,6)])
print(var1**var2)

[[     8   1024 279936]
 [     1   2187  15625]]


In [105]:
import numpy as np
var1=np.array([(2,4,6),(1,3,5)])
var2=np.array([(3,5,7),(8,7,6)])
print(var1//var2)

[[0 0 0]
 [0 0 0]]


### print all the arrays in single line


In [106]:
import numpy as np
var1=np.array([(2,4,6),(1,3,5)])
print(var1)
print(var1.ravel())

[[2 4 6]
 [1 3 5]]
[2 4 6 1 3 5]


### addition of axises

In [107]:
import numpy as np
var1=np.array([(2,4,6),(1,3,5)])
print(var1.sum(axis=1))
print(var1.sum(axis=0))

[12  9]
[ 3  7 11]
